CREATE TABLE IF NOT EXISTS roles(
    id INT PRIMARY KEY AUTO_INCREMENT NOT NULL,
    role VARCHAR (50) NOT NULL
);
INSERT INTO roles (role)
VALUES("ROLE_USER");
INSERT INTO roles (role)
VALUES("ROLE_ADMIN");