CREATE TABLE IF NOT EXISTS pessoa (
  id INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
  cpf VARCHAR(11) UNIQUE NULL,
  nome VARCHAR(255) NOT NULL,
  contato VARCHAR(11) NULL,
  email VARCHAR(255) UNIQUE NOT NULL,
  genero VARCHAR(45) NOT NULL,
  dataNascimento VARCHAR(15) NOT NULL,
  cep VARCHAR(8) NULL,
  rua VARCHAR(255) NULL,
  bairro VARCHAR(45) NULL,
  cidade VARCHAR(45) NULL,
  estado VARCHAR(2) NULL,
  nrResidencia VARCHAR(45) NULL,
  usuario VARCHAR(45) NULL,
  senha VARCHAR(255) NOT NULL,
  role VARCHAR(45) NOT NULL
);
