CREATE TABLE IF NOT EXISTS empresa (
  id INT UNIQUE NOT NULL AUTO_INCREMENT,
  cnpj VARCHAR(45) PRIMARY KEY  NOT NULL,
  nome VARCHAR(255) UNIQUE NOT NULL,
  cep VARCHAR(8) NOT NULL,
  UF VARCHAR(2) NULL,
  cidade VARCHAR(255) NULL,
  endereco VARCHAR(255) NULL,
  email VARCHAR(255) NULL,
  contato VARCHAR(11) NULL
 )
